apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: redis
  name: redis
spec:
# schedulerName: <scheduler_name> # custom scheduler
  containers:
    image: redis
    name: redis
    volumeMounts:
    - mountPath: /opt
      name: data-vol
  volumes:
  - name: data-vol
    persistentVolumeClaim:
      claimName: myclaim
  # volumes:
  # - name: data-vol
  # hostPath:
  #   path: /data
  #   type: Directory
  