apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
spec:
  containers:
    name: simple-pod
    image: simple-pod
    ports:
      - containerPort: 8080
    env:
      - name: APP_COLOR
        value: pink
    # for configmaps
    envFrom:
      configMapRef:
        name: app-config
      # OR
    env:
    - name: APP_COLOR
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: APP_COLOR

    # For secrets use similar key words configmap=secret